services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - VITE_APP_NAME=Resume Scanner
      - VITE_APP_VERSION=1.0.0
    networks:
      - frontend-network
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  frontend-network:
    driver: bridge
