services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
        - VITE_APP_NAME=${VITE_APP_NAME:-Resume Scanner}
        - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  frontend-network:
    driver: bridge
