# ===========================================
# DOCKER COMPOSE - REPLIT VERSION
# ===========================================
# This file orchestrates all services for Replit deployment

services:
  # ===========================================
  # BACKEND API SERVICE
  # ===========================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: myaihr-backend
    ports:
      - "8000:8000"
    environment:
      # Database Configuration
      - DATABASE_URL=sqlite:///./database/resume.db
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-production-key-change-this-now}
      - ACCESS_TOKEN_EXPIRE_DAYS=${ACCESS_TOKEN_EXPIRE_DAYS:-7}
      
      # AI/LLM Configuration
      - OLLAMA_API=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.2:3b}
      
      # File Upload Configuration
      - UPLOAD_DIR=${UPLOAD_DIR:-./uploads/resumes}
      - PROFILE_PHOTO_DIR=${PROFILE_PHOTO_DIR:-./uploads/profile_photos}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      
      # User Quota Configuration
      - MAX_MONTHLY_SCANS=${MAX_MONTHLY_SCANS:-10}
      
      # OAuth Configuration
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
      - LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
    
    volumes:
      - uploads:/app/uploads
      - database:/app/database
    
    depends_on:
      - ollama
      - redis
    
    restart: unless-stopped

  # ===========================================
  # OLLAMA AI SERVICE
  # ===========================================
  ollama:
    image: ollama/ollama:latest
    container_name: myaihr-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  # ===========================================
  # REDIS CACHE SERVICE
  # ===========================================
  redis:
    image: redis:7-alpine
    container_name: myaihr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # ===========================================
  # FRONTEND SERVICE
  # ===========================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myaihr-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
      - REACT_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - REACT_APP_LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
    depends_on:
      - backend
    restart: unless-stopped

# ===========================================
# VOLUMES
# ===========================================
volumes:
  uploads:
  database:
  ollama_data:
  redis_data:
