# Production override for docker-compose.yml
services:
  backend:
    # Override volumes for production (no source code mounting)
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./database:/app/database
    environment:
      - NODE_ENV=production
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
    # Override command for production with Gunicorn
    command: ["gunicorn", "app:app", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]
    # Add resource limits for production
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

